# Add the contents of this file to your Home Assistant configuration.yaml
# Uncomment the modbus connection option you will use (USB adapter or LAN - not both!)
# Source https://github.com/StealthChesnut/HA-FoxESS-Modbus
# This file isn't a valid configuration file!

#FoxESS Plugin - Modbus Configuration and Mappings
#modbus: !include custom_components\HA-FoxESS-Modbus\modbusUSB.yaml
#modbus: !include custom_components\HA-FoxESS-Modbus\modbusLAN.yaml
sensor: !include custom_components\HA-FoxESS-Modbus\sensors.yaml
